### ISSUE TITLE
setWechatConfig怎么用？

### ISSUE THREAD

**Issue by Ooomelette** [fa-ge/NativeShare#1]
我在控制台中没打印到这个方法~你这个实例方法怎么使用呢？

**Comment by Ooomelette** [comment]
我在你的NativeShare/src/Wechat.js 也没有看到相关的配置覆盖~

**Comment by fa-ge** [comment]
真是不好意思。昨天刚刚修改了新的api，readme还没有写完。今天一定补完。
new NativeShare({wechatConfig: {}})。目前改成这种形式了。感觉更好

**Comment by Ooomelette** [comment]
我看了源码，已经解决了，给你点个赞~封装的不错，不过建议把wx.error 把出错暴露下，分享失败的时候，至少知道哪里出错了，不用去猜~
