### ISSUE TITLE
关于QQ分享设置文案的问题

### ISSUE THREAD

**Issue by Ooomelette** [fa-ge/NativeShare#10]
问题：我这边遇到一个情景，当在QQ中打开了h5页面，做了QQ的初始化，当我跟用户进行了一些交互之后，我的分享文案已经改变了，但是我不使用页面自己的按钮进行分享，使用QQ右上角的分享功能弹出分享框，这时候，你分享出去的文案还是初始化的文案
原因：在QQ初始化之后，调用setShareData设置文案，并不会重新执行mqq.data.setShareInfo方法，当我们去执行call的时候，才会执行分mqq.data.setShareInfo，导致如果我使用qq右上角的分享，后面设置的文案并没有生效

**Comment by Ooomelette** [comment]
@fa-ge

**Comment by fa-ge** [comment]
你应该是哪里搞错了，setShareData是会执行mqq.data.setShareInfo方法的！可以试试这个链接http://7xjkrd.com1.z0.glb.clouddn.com/index.html

**Comment by Ooomelette** [comment]
android 重写了share类的setshareData方法，在ios 的QQ中 ，你没有重写 setShareData，
https://github.com/fa-ge/NativeShare/blob/master/src/QQIos.js

**Comment by fa-ge** [comment]
ios不需要重写setshareData，因为ios有mqq.ui.setOnShareHandler方法，他接受一个方法作为参数，当你点击分享框中的某个分享按钮时会触发这个回调方法。因为shareData 和 this._shareData是指向同一个对象的，所以shareData一直会是最新的值。所以在setShareData方法里我只要改变this._shareData就可以了。

**Comment by Ooomelette** [comment]
ok，谢啦
