### ISSUE TITLE
安卓qq分享没有任何效果

### ISSUE THREAD

**Issue by Anehta** [fa-ge/NativeShare#11]
安卓qq分享没有任何效果。。什么都没调用起来

**Comment by fa-ge** [comment]
http://7xjkrd.com1.z0.glb.clouddn.com/index.html

**Comment by fa-ge** [comment]
http://7xjkrd.com1.z0.glb.clouddn.com/index.html
你可以试一下这个链接。关于android qq的问题，我在文档中有提，你可以看看我说的。这个可能跟域名有关系。

**Comment by Anehta** [comment]
@fa-ge 你的这个确实能顺利调起安卓的分享。

**Comment by fa-ge** [comment]
这个里面的代码和我文档中的demo里的代码是一模一样的。唯一的区别就是域名了。你可以把demo拷贝到你们的服务器下看可不可以

**Comment by Anehta** [comment]
@fa-ge 这么诡异的么。。。这分享网址还有白名单啊。那去哪里添加进白名单呢。

**Comment by fa-ge** [comment]
我猜的啦。。这份白名单应该是QQ内部维护的。我们看不见的。

**Comment by Anehta** [comment]
@fa-ge 啊啊啊啊啊。就安卓不好。。其它都挺好的。真坑啊。

**Comment by fa-ge** [comment]
你们公司的服务器下试了吗？也许可以！七牛就可以

**Comment by Anehta** [comment]
@fa-ge 并不可以啊。。哎

**Comment by fa-ge** [comment]
先不要慌，你可以把你们的页面放到七牛上(我跟七牛啥关系没有)，看看行不行。

**Comment by Anehta** [comment]
@fa-ge 七牛给我的域名竟然被腾讯管家屏蔽了

**Comment by fa-ge** [comment]
@Anehta 你要不加下我QQ把，我个人资料里有我QQ邮箱。我刚刚试了一下公司的域名，也是可以的。

**Comment by Anehta** [comment]
@fa-ge 我是发现问题了。我们公司的域名是.tv .cc的，你的demo的域名是.io的，测试成功的都是.com .cn的..所以显而易见。。。。
