### ISSUE TITLE
深坑

### ISSUE THREAD

**Issue by Ooomelette** [fa-ge/NativeShare#12]
在微信下有个巨大的深坑，找了近一个晚上才找到。Object.defineProperty(wxShareData, 'trigger', { 方法里面assign(wxShareData, shareData) 这句，在shareDate里面没有imgUrl字段，也就是说wxShareData里面的imgUrl永远没法被更改，对于单页面的分享，分享出去的图只会是shareDate里面没有imgUrl字段的图。

**Comment by Anehta** [comment]
我这里是正常的啊。

**Comment by fa-ge** [comment]
不好意思，看出错误了！今天改

**Comment by Ooomelette** [comment]
再给以个建议，其实在微信的jssdk里面，可以调起微信的分享面板~看需求咯，不过作为你这个插件，我觉得你可以把这个功能也搞上去，为了保证和其他的一致性

**Comment by Ooomelette** [comment]
既然都说到这里了，我其实还有一些建议，也是我在用vue做spa的时候发现的。在你这个插件做第一次初始化的时候，其实我并不知道，相应的jssdk是否加载完毕，如果这个jssdk没有加载完毕的情况下，我们是没有办法去设置分享的文案的，并且会报错。因为在spa里面的，vue，render只会，肯定会执行一次分享的初始化，这时候，你的jssdk并没有加载完毕，所以肯定会出错~望优化，希望git主能把这个做成一个在移动端完全独立的native库，看好你！

**Comment by fa-ge** [comment]
jssdk能调用起微信分享，这个还真不知道。
关于你说的jssdk如果没加载完成就去调用setShareData和call方法都是不会出问题的，只是此时没有真正的设置好文案。当jssdk这个js加载完成后，此时会设置你的文案。所以应该没什么问题。

**Comment by Ooomelette** [comment]
比如我们以安卓的QQ分享为例子，当我new实例对象之后，立马去做 setShareData 这个方法，我们会进入到mqq.data.setShareInfo，这里mqq，并没有，所有抛出异常到catch里面，但是我这时候的分享文案设置肯定是没有成功的，用户直接去分享，肯定是没办法拿到我们设定的信息

**Comment by fa-ge** [comment]
不会啊，你看我的init方法里有在下载完js后调用setShareData方法的。

**Comment by fa-ge** [comment]
@Ooomelette 关于微信图片设置的问题已经改了。发布了。。更新一下包就可以了
