### ISSUE TITLE
请问可以直接在react中使用吗？

### ISSUE THREAD

**Issue by yaominguo** [fa-ge/NativeShare#13]
问可以直接在react中使用吗？
如果可以的话是怎么个使用法呢？
还是说只能封装成一个额外的文件来调用。

**Comment by fa-ge** [comment]
可以。使用方法很简单啊。
import NativeShare from 'nativeshare'

**Comment by yaominguo** [comment]
不好意思，我已经解决了，还是谢谢你的回答。
原来的
`onClick={()=>{call('weibo')}}`
改成
`onClick={()=>{nativeShare.call('weibo')}}`
就可以了！
