### ISSUE TITLE
移动端 chrome 目前还没支持吗

### ISSUE THREAD

**Issue by 208098588** [fa-ge/NativeShare#15]

**Comment by 208098588** [comment]
qq 、qq空间 和微博 可以，其它不行、

**Comment by 208098588** [comment]
ios 的 微信内置，qq内置 都不能分享呀

**Comment by fa-ge** [comment]
chrome还没支持。QQ和QQ空间几乎在所有浏览器(不包括webview)中都是可以的。

**Comment by fa-ge** [comment]
ios内置只能设置文案，qq内置的话需要.com域名的支持，因为demo是跑在.io域名下的，所以不支持。我在文档中都有写到。

**Comment by 208098588** [comment]
好的 谢谢
