### ISSUE TITLE
模块导入引用的时候 iphoneQQ浏览器无法调起 报错

### ISSUE THREAD

**Issue by Shadownc** [fa-ge/NativeShare#16]
Can't find variable:browser

**Comment by fa-ge** [comment]
QQ浏览器哪个版本？

**Comment by Shadownc** [comment]
7.7.2.3549 ios 是因为模块导入引起的吗？我用你那个demo是可以唤起的

**Comment by fa-ge** [comment]
那你是怎么导入的？怎么使用的？提供尽量完整的信息

**Comment by Shadownc** [comment]
在vue-cli导入 npm i vue-nativeshare -S 导入
import NativeShare from 'nativeshare'
我直接在mounted里面调用
var nativeShare = new NativeShare()
       var shareData = {
       title: '',
       desc: '',
       // 如果是微信该link的域名必须要在微信后台配置的安全域名之内的。
       link: window.location.href,
       icon: '',
       // 不要过于依赖以下两个回调，很多浏览器是不支持的
       success: function () {
       alert('success')
       },
       fail: function () {
       alert('fail')
       }
       }
       nativeShare.setShareData(shareData)
       try {
       nativeShare.call('wechatTimeline')
       } catch (err) {
       // 如果不支持，你可以在这里做降级处理
       alert(err.message)
       }

**Comment by fa-ge** [comment]
你下载的模块错了呀，你看报错，nativeshare一定没解析到

**Comment by Shadownc** [comment]
额 那应该咋下载？在安卓手机上是可以唤起的

**Comment by NoraGithub** [comment]
相同问题
  请问怎么解决的？ @Shadownc @fa-ge
