### ISSUE TITLE
微信内浏览器分享无效

### ISSUE THREAD

**Issue by licdream** [fa-ge/NativeShare#18]
微信内浏览器所有分享功能无效，微信版本：6.5.13

**Comment by fa-ge** [comment]
我的demo微信分享本身就不成功的。微信分享需要提供appid等配置。配置后是可以的

**Comment by Geocld** [comment]
遇到同样的问题，IOS11 Safari下无法启动微信分享，已经配置appid、nonceStr、signature、timestamp

**Comment by fa-ge** [comment]
Safari下就是唤醒不了微信的 @Geocld

**Comment by licdream** [comment]
微信浏览器内分享，无论nativeShare.call()里面命令参数是否设置“wechatFriend”都相当于只是设置分享标题是吗？如果是这样的话，那微信自带浏览器是指的哪个部分？

**Comment by fa-ge** [comment]
设置分享文案用的是命令nativeShare.setShareData方法，微信自带浏览器不能弹出系统的分享组件，所以call方法其实是无效的。 @licdream
