### ISSUE TITLE
微信问题

### ISSUE THREAD

**Issue by wangwinterice** [fa-ge/NativeShare#20]
大神，在ios中的safari和qq浏览器都唤不出微信啊

**Comment by fa-ge** [comment]
你QQ浏览器啥版本？我这边可以啊。safari本来就换不起微信的

**Comment by wangwinterice** [comment]
7.9.0.3650

**Comment by fa-ge** [comment]
你打开的是readme.md中的demo吗？有没有具体的报错信息

**Comment by wangwinterice** [comment]
使用手机上的qq扫描二维码，打开有7个按钮的demo页面
点击微信好友和朋友圈会报这样的错“the browser may not support command wechatfriend“，然后没有唤起微信；
点击qq或qq空间也会报“the browser may not support command qqfriend“，但是能唤起qq；

**Comment by fa-ge** [comment]
在一些不支持唤醒qq或者qq空间的浏览器中，插件会尝试通过schema的方式打开QQ，qq空间，但是我并不知道到底有没有唤醒成功了。所以我会一律提示没唤醒成功。readme.md中有说明。
