### ISSUE TITLE
请问angular2可以调用这个插件吗？怎么调用呢

### ISSUE THREAD

**Issue by Helongzhou** [fa-ge/NativeShare#22]

**Comment by fa-ge** [comment]
可以。跟你用什么框架没有关系。调用方式看readme.md说明

**Comment by Helongzhou** [comment]
作者你好，因为angular2是使用typescript编译的，好像没办法直接使用js文件，我尝试在index.html引入NativeShare.js，然后在component.ts里面使用会报错，不知道您有在angular2的项目里使用过吗？可以分享一下您的使用经验吗？

**Comment by fa-ge** [comment]
该插件是兼容amd,commonjs,ES6模块引入的机制的

**Comment by Helongzhou** [comment]
目前我是按demo在index.html引入，在script标签里直接调用js接口，能实现分享功能，我再去了解一下‘amd,commonjs,ES6模块引入的机制‘，看怎么改成合理的引入，谢谢。

**Comment by fa-ge** [comment]
一样的啊。你ts怎么引其他模块，你就这么引这个模块啊
