### ISSUE TITLE
为什么我加入到网页里面就唤醒不了

### ISSUE THREAD

**Issue by lxk520** [fa-ge/NativeShare#24]
单独一个页面就可以唤醒  加入到我网页的html里面就唤醒不了 是怎么回事

**Comment by fa-ge** [comment]
有没有在线demo

**Comment by lxk520** [comment]
@fa-ge 已经解决了 谢谢  之前看过很多类似的插件 就是支持的浏览器太少  感谢楼主 希望以后回更好
