### ISSUE TITLE
今天发现微信内浏览器分享出去的是当前网页

### ISSUE THREAD

**Issue by CooperHush** [fa-ge/NativeShare#28]
微信内浏览器分享出去的是当前网页，不是自定义的标题和链接

**Comment by fa-ge** [comment]
你可以去微信开发者工具上看看到底报啥错？是不是配置有问题

**Comment by CooperHush** [comment]
好像是使用的IP访问的问题，必须要在正式域名里访问才行

**Comment by fa-ge** [comment]
对的，你的域名还必须是在你们微信的配置后台里配置为安全域名才可以！
