### ISSUE TITLE
iPhone7 QQ浏览器分享到微博没有反应？

### ISSUE THREAD

**Issue by CooperHush** [fa-ge/NativeShare#3]
iPhone7 QQ浏览器分享到微博没有反应、UC、360、Safari都可以

**Comment by fa-ge** [comment]
我这边6s在QQ浏览器的情况是点了微博分享，过了两三秒左右会弹出一个分享成功的toast！不知道你有没有注意？

**Comment by CooperHush** [comment]
嗯，我测了下，等了五六秒才弹出分享成功的toast.

**Comment by CooperHush** [comment]
好像是网络问题，可能与请求的数据大小有关，我的分享含有图片，速度就满了。我换了4G下就快了许多.
