### ISSUE TITLE
UC分享没反应了

### ISSUE THREAD

**Issue by cxqian** [fa-ge/NativeShare#4]
UC内部是不是修改了调用方法

**Comment by Ooomelette** [comment]
我这边也发现了，uc内部调用，在最新版本进入了ucweb.startRequest('shell.page_share', [
            shareData.title,
            shareData.desc,
            shareData.link,
            toApp,
            '',
            shareData.from,
            shareData.icon,
        ])
这个方法，但是没有正确打开qq和微信，并且没有抛出异常

**Comment by zhengxiansen** [comment]
iOS正常，安卓不行了

**Comment by xiaodoulala** [comment]
安卓的QQ 客户端用不了

**Comment by fa-ge** [comment]
你的QQ什么版本？ @xiaodoulala

**Comment by xiaodoulala** [comment]
@fa-ge 几个朋友用安卓手机帮我测试都不行，我是用script引入NativeShare.js，ios的微信也用不了，QQ版本是V7.1.03175

**Comment by fa-ge** [comment]
直接扫demo中的二维码，那个案例能用吗？ @xiaodoulala

**Comment by xiaodoulala** [comment]
@fa-ge demo里点QQ分享也是没反应

**Comment by fa-ge** [comment]
在微信中是没法调用起分享组件的，微信中只能设置文案。而且分享的url必须是你们公众号的安全域名中的。所以在微信中确实是没反应的。至于QQ客户端没反应问题，我晚上会看一下。

**Comment by fa-ge** [comment]
@xiaodoulala 文档有更新你可以看看，关于android QQ分享比较复杂。

**Comment by fa-ge** [comment]
最新版本UC已经没问题了
