### ISSUE TITLE
NUXT.JS 项目运行直接导致无响应,项目直接跑不起来了,也没有提示错误

### ISSUE THREAD

**Issue by lihaibin20180808** [fa-ge/NativeShare#59]
![微信截图_20190726205025](https://user-images.githubusercontent.com/43167902/61953067-09035e80-afe8-11e9-9c16-af9e665bbf17.png)
![微信截图_20190726205215](https://user-images.githubusercontent.com/43167902/61953073-0bfe4f00-afe8-11e9-8774-62a287c68be3.png)

nuxt的项目是否可以使用?

**Comment by Maple13** [comment]
Nuxt中使用方法
```ES6
# 引入
let NativeShare;

if (process.browser) {
   NativeShare = require('nativeshare');
}

# 使用
this.nativeShare = new NativeShare.default() // 这里是关键
this.nativeShare.setShareData({ })
```

**Comment by lihaibin20180808** [comment]
{
src: '~/plugins/nativeShare',
ssr: false <=== 需要添加这个,这是关键
},

**Comment by Maple13** [comment]
OK, 我那种是直接引入使用的, 你这种是以plugins方式引入, 你的方法更好
