### ISSUE TITLE
微信的应该怎么处理，降级处理是什么意思

### ISSUE THREAD

**Issue by kitymore** [fa-ge/NativeShare#6]

**Comment by kitymore** [comment]
这个问题应该怎么处理

**Comment by fa-ge** [comment]
微信分享需要配置wechatConfig参数，文档中有写。但是微信分享不能调起原生的分享组件，只能设置分享文案。所以如果是微信分享最好有一个指向右上角的箭头提示用户分享！降级处理当用户的浏览器不支持调用原生的分享组件你需要换一种形式提示用户分享！
