### ISSUE TITLE
我想去掉调用浏览器原生的分享，不知道怎么改啊  js小白 谢谢大神求助

### ISSUE THREAD

**Issue by sunke0726** [fa-ge/NativeShare#7]

**Comment by fa-ge** [comment]
什么意思，你不去调用call方法就不会去NativeShare就不会去调用浏览器原声的分享呀。如果你只是想设置文案，你可以只调用setShareData方法

**Comment by sunke0726** [comment]
哇 这块就回复了 懂您的意思了，但是我这样写了以后，
分享的连接该怎么写啊 我这样写不生效：onclick="setShareData('wechatFriend')


引入js:
    <script type="text/javascript" src="/js/nativeShare.js"></script>
    <script  type="text/javascript">
        //分享
        var nativeShare = new NativeShare()
        nativeShare.setShareData({
            icon: 'https://pic3.zhimg.com/v2-080267af84aa0e97c66d5f12e311c3d6_xl.jpg',
            link: 'https://github.com/fa-ge/NativeShare',
            title: 'NativeShare',
            desc: 'NativeShare是一个整合了各大移动端浏览器调用原生分享的插件',
            from: '@fa-ge',
        })
    </script>

html
                                <a href="javascript:void(0)" class="a_01 weixinOther" onclick="setShareData('wechatFriend')">微信好友</a>
                                <a href="javascript:void(0)" class="a_01 safari-wx-btn" style="display:none">微信好友</a>
                                <a href="javascript:void(0)" class="a_04" onclick="setShareData('qqFriend')">QQ空间</a>
                                <a href="javascript:void(0)" class="a_03" onclick="setShareData('qZone')">QQ好友</a>
                                <a href="javascript:void(0)" class="a_05" onclick="setShareData('weibo')">新浪微博</a>

**Comment by sunke0726** [comment]
分享按钮用这个方法不生效：    onclick="setShareData('wechatFriend')" 
setShareData is not defined

**Comment by fa-ge** [comment]
setShareData是NativeShare实例的方法。你这样写调用的是window下的setShareData肯定 undefined啊。在demo中，`var nativeShare = new NativeShare()
nativeShare.setShareData({
icon: 'https://pic3.zhimg.com/v2-080267af84aa0e97c66d5f12e311c3d6_xl.jpg',
link: 'https://github.com/fa-ge/NativeShare',
title: 'NativeShare',
desc: 'NativeShare是一个整合了各大移动端浏览器调用原生分享的插件',
from: '@fa-ge',
})` 这样就调用了setShareData方法啊，设置了文案。你不点按钮也没有关系。但是只是这样设置文案其实是有问题的。像浏览器没有提供这样的方法只设置文案，不唤起分享组件。所以如果不唤起只设置了文案其实也是白搭。分享出去的时候设置的文案是无效的

**Comment by sunke0726** [comment]
小白想知道怎么唤起分享组件........

**Comment by sunke0726** [comment]
使用这个方法么？getShareData()，我这样写貌似也不生效...
按钮：
onclick="getShareData('wechatFriend')"

js：
function getShareData(command) {
    try {
        nativeShare.getShareData(command)
    } catch (err) {
        //微信不能使用的情况下
        wenxiOther()
    }
}

**Comment by fa-ge** [comment]
我算是看明白了。。你题目当中说的我想去掉浏览器的分享组件我理解了是要删掉，应该是你想去调浏览器的分享组件吧。调用浏览器的分享组件就用call方法呀。`	
nativeShare.call()
 // 如果是要指定分享的话, 就nativeShare.call('wechatFriend')
// 支持的命令在文档中都有些
`
