### ISSUE TITLE
在safari和微信中都不能分享给微信好友，请问有人有解决办法吗？

### ISSUE THREAD

**Issue by 15120822558** [fa-ge/NativeShare#74]
在safari和微信中都不能分享给微信好友，请问有人有解决办法吗？

**Comment by fa-ge** [comment]
低版本的safari不支持分享。微信中是能分享的，demo中不能分享因为公众号后台没有配白名单域名。具体看readme

**Comment by 15120822558** [comment]
现在的版本还没有支持在百度APP中分享到微信好友？？



在 2020-08-07 10:44:00，"fage" <notifications@github.com> 写道：

低版本的safari不支持分享。微信中是能分享的，demo中不能分享因为公众号后台没有配白名单域名。具体看readme

**Comment by fa-ge** [comment]
> 现在的版本还没有支持在百度APP中分享到微信好友？？ 在 2020-08-07 10:44:00，"fage" <notifications@github.com> 写道： 低版本的safari不支持分享。微信中是能分享的，demo中不能分享因为公众号后台没有配白名单域名。具体看readme — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ios上新系统是支持百度APP去分享到好友的，android不支持。
