### ISSUE TITLE
关于在android中QQ无法分享的问题，我已经找到方案了

### ISSUE THREAD

**Issue by Ooomelette** [fa-ge/NativeShare#8]
android中，你调取的的通用api，无法实现，你可以调用data里面的setShareInfo，亲测有效。坑成狗，具体详情，请看qq的文档http://open.mobile.qq.com/api/mqq/index#api:setShareInfo

**Comment by Ooomelette** [comment]
@fa-ge

**Comment by fa-ge** [comment]
非常感谢。晚上试一下

**Comment by fa-ge** [comment]
好坑，这个方法以前试过！今天才发现好像以ip去访问页面是不会生效的，放到域名下就可以啦！
