### ISSUE TITLE
本地测试无效果及vue项目引用无效果

### ISSUE THREAD

**Issue by liyawen1110** [fa-ge/NativeShare#82]
hello，我想请问下，我直接访问github的demo地址，在ios safari中可以唤起浏览器自带的分享。但是把demo代码复制到本地，用编辑器自带的服务器去跑，却没有效果。此外在vue项目import引入，用devserver去跑也没有效果，都走了catch，提示“the browser may not support command wechatfriend!”，望大神解答，谢谢。

**Comment by fa-ge** [comment]
需要https

**Comment by liyawen1110** [comment]
您的意思是，需要地址是https才能支持这些api是嘛

**Comment by fa-ge** [comment]
safari那个需要https的支持，其他的有些跟域名相关

**Comment by liyawen1110** [comment]
好的，谢谢，我试一下

**Comment by liyawen1110** [comment]
safari可以的，谢谢
