### ISSUE TITLE
请问这个支持https协议的么？http 貌似不成功呢

### ISSUE THREAD

**Issue by gps-336699** [fa-ge/NativeShare#84]
请问这个支持https协议的么？

**Comment by fa-ge** [comment]
safari，chrome分享需要https环境下才能成功

**Comment by gps-336699** [comment]
> safari，chrome分享需要https环境下才能成功

感谢回复,我是在chrome浏览器下，点击的时候直接提示: the browser may not support command default!

**Comment by gps-336699** [comment]
> safari，chrome分享需要https环境下才能成功
好的，谢谢您的帮助，您的插件非常棒，感谢
