### ISSUE TITLE
我在域名为http的状态下无法调起。如何才能在http下调用呢。有没有好的解决方案

### ISSUE THREAD

**Issue by zhanghuiqi205** [fa-ge/NativeShare#85]

**Comment by fa-ge** [comment]
具体哪个环境？

**Comment by zhanghuiqi205** [comment]
就是苹果手机的自带浏览器。还有我安装的alook浏览器。目前是两个在https下都可以。http就不行。我看到之前的问题。有说的要使用https，我想知道是如何才能在http下也可以正常使用。麻烦您看一下。谢谢

**Comment by zhanghuiqi205** [comment]
> 具体哪个环境？

就是苹果手机的自带浏览器。还有我安装的alook浏览器。目前是两个在https下都可以。http就不行。我看到之前的问题。有说的要使用https，我想知道是如何才能在http下也可以正常使用。麻烦您看一下。谢谢

**Comment by fa-ge** [comment]
浏览器要求，没有解决办法

**Comment by zhanghuiqi205** [comment]
> 浏览器要求，没有解决办法

好的。谢谢你。麻烦了
