### ISSUE TITLE
微信参数初始化能不能加个方法。

### ISSUE THREAD

**Issue by Anehta** [fa-ge/NativeShare#9]
因为我获取服务器参数是异步的。在创建出NativeShare之后才能获取到该有的东西然后再去初始化么。所以能不能搞个方法单独初始化微信的参数。

**Comment by fa-ge** [comment]
可以。晚上在加吧

**Comment by fa-ge** [comment]
可以了，调用方式nativeShare.setConfig({wechatConfig: ...})文档上有更新

**Comment by Anehta** [comment]
谢谢啦
